version: '3.4'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: hot-reload
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    tty: true
