name: Terraform Apply

on:
  push:
    branches:
      - master
    paths:
    - 'terraform/**'

env:
  GCP_PROJECT: sample-283906

jobs:
  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
    - uses: actions/checkout@v2

    - name: Generate credentials.json from secrets
      run: echo ${{ secrets.TF_SA_KEY }} | base64 -d | tee ./credentials.json >/dev/null

    - name: apply
      run: |
        docker run --rm --entrypoint "" -w /terraform \
        -v $PWD:/terraform \
        -e GOOGLE_APPLICATION_CREDENTIALS=/terraform/credentials.json \
        hashicorp/terraform:light sh -c " \
        terraform init && \
        terraform fmt -check && \
        terraform apply -auto-approve -no-color"